on:
  push:
    branches:
      - main
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
      - name: Read local package version
        id: read-local-version
        run: |
          echo "::set-output name=version::$(jq -r .version package.json)"
      - name: Read published package version
        id: read-published-version
        run: |
          version=$(pnpm view ${{ github.repository }} version --registry https://npm.pkg.github.com 2>/dev/null || echo "")
          echo "::set-output name=version::$version"
      - name: Install and publish
        if: steps.read-local-version.outputs.version != steps.read-published-version.outputs.version
        run: |
          pnpm install
          pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Prune files
        run: bash scripts/prune.sh

      - name: Bake and push Docker image
        uses: docker/bake-action@v6
        with:
          push: true
          source: .
          targets: pandvil-gha
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file-tags }}
            ${{ steps.meta.outputs.bake-file-labels }}
          set: |
            *.platform=linux/amd64,linux/arm64
